ALTER TABLE `User`
  ADD COLUMN `lastLoginAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE `Province`
  ADD COLUMN `reputation` INTEGER NOT NULL DEFAULT 1000,
  ADD COLUMN `magicRep` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `militaryRep` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `attacksMade` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `attacksSuffered` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `attackWins` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `attacksSufferedLost` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `metalChange` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `metalTotal` INTEGER NOT NULL DEFAULT 0;

ALTER TABLE `Attack`
  ADD COLUMN `extraIncome` DOUBLE NOT NULL DEFAULT 0;

ALTER TABLE `AgeResult`
  ADD COLUMN `pID` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `userID` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `userName` VARCHAR(16) NULL,
  ADD COLUMN `kiID` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `acres` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `thieveryRank` VARCHAR(40) NULL,
  ADD COLUMN `thieveryPoints` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `magicRank` VARCHAR(40) NULL,
  ADD COLUMN `magicPoints` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `militaryPoints` INTEGER NOT NULL DEFAULT 0;

CREATE TABLE `KingdomNews` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `kiID` INTEGER NOT NULL,
  `message` VARCHAR(500) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `KingdomNews_kiID_id_idx` (`kiID`, `id`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `DeadMilitary` (
  `deadMilID` INTEGER NOT NULL AUTO_INCREMENT,
  `pID` INTEGER NOT NULL,
  `mID` INTEGER NOT NULL,
  `ticks` INTEGER NOT NULL DEFAULT 24,
  `num` INTEGER NOT NULL DEFAULT 0,
  UNIQUE INDEX `DeadMilitary_pID_mID_ticks_key` (`pID`, `mID`, `ticks`),
  INDEX `DeadMilitary_pID_idx` (`pID`),
  INDEX `DeadMilitary_mID_idx` (`mID`),
  PRIMARY KEY (`deadMilID`),
  CONSTRAINT `DeadMilitary_pID_fkey` FOREIGN KEY (`pID`) REFERENCES `Province` (`pID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `DeadMilitary_mID_fkey` FOREIGN KEY (`mID`) REFERENCES `MilitaryT` (`mID`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ForumThread` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `scope` VARCHAR(10) NOT NULL,
  `kiID` INTEGER NOT NULL DEFAULT 0,
  `authorPID` INTEGER NOT NULL,
  `author` VARCHAR(40) NOT NULL,
  `title` VARCHAR(120) NOT NULL,
  `locked` BOOLEAN NOT NULL DEFAULT false,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  INDEX `ForumThread_scope_kiID_updatedAt_idx` (`scope`, `kiID`, `updatedAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ForumPost` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `threadId` INTEGER NOT NULL,
  `authorPID` INTEGER NOT NULL,
  `author` VARCHAR(40) NOT NULL,
  `body` TEXT NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `ForumPost_threadId_id_idx` (`threadId`, `id`),
  PRIMARY KEY (`id`),
  CONSTRAINT `ForumPost_threadId_fkey` FOREIGN KEY (`threadId`) REFERENCES `ForumThread` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
